services:
  ts-rsync:
    image: tailscale/tailscale:stable
    container_name: ts-rsync
    hostname: tailscale-backup-raspberry
    env_file: "./secrets/blueberry.env"
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-rsync-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  rsync-server:
    build:
      # make it build on ARM architecture
      context: https://github.com/eea/eea.docker.rsync.git
      dockerfile: Dockerfile
    container_name: rsync-server
    command: server
    env_file: "./secrets/blueberry.env"
    volumes:
      - "/mnt/lacie-hdd/backup:/data/"
    network_mode: service:ts-rsync
    restart: unless-stopped
    depends_on:
      - ts-rsync

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 7007
    environment:
      - DOZZLE_HOSTNAME=backup
      - DOZZLE_NO_ANALYTICS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s

  ssht-dozzle:
    image: jnovack/autossh:2.1.0
    container_name: ssht-dozzle
    env_file: "./secrets/blueberry.env"
    restart: unless-stopped
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      dozzle:
        condition: service_healthy

volumes:
  ts-rsync-state:
    name: ts-rsync-state
